services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fuse-container  # 컨테이너 이름을 fuse-con으로 설정
    volumes:
      - .:/home/ubuntu/project
    tty: true
    stdin_open: true  # 표준 입력을 열어 대화형으로 사용